/**
 * Rotas de SEO - Sitemap.xml e Robots.txt
 */

import { Hono } from 'hono';
import type { Env } from '../index';

export const seoRoutes = new Hono<{ Bindings: Env }>();

// ==================== SITEMAP.XML ====================
seoRoutes.get('/sitemap.xml', async (c) => {
  try {
    const db = c.env.DB;
    
    // Buscar configurações do site
    const settingsResult = await db.prepare(
      "SELECT value FROM settings WHERE key = 'site_url'"
    ).first();
    const siteUrl = (settingsResult?.value as string) || 'https://cms-site.pages.dev';
    
    // Buscar páginas publicadas
    const pages = await db.prepare(`
      SELECT slug, updated_at FROM pages 
      WHERE status = 'published' 
      ORDER BY updated_at DESC
    `).all();
    
    // Buscar posts publicados
    const posts = await db.prepare(`
      SELECT slug, updated_at FROM posts 
      WHERE status = 'published' 
      ORDER BY updated_at DESC
    `).all();
    
    // Gerar XML
    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
    
    // Homepage
    xml += `  <url>\n`;
    xml += `    <loc>${siteUrl}/</loc>\n`;
    xml += `    <changefreq>daily</changefreq>\n`;
    xml += `    <priority>1.0</priority>\n`;
    xml += `  </url>\n`;
    
    // Blog index
    xml += `  <url>\n`;
    xml += `    <loc>${siteUrl}/blog</loc>\n`;
    xml += `    <changefreq>daily</changefreq>\n`;
    xml += `    <priority>0.9</priority>\n`;
    xml += `  </url>\n`;
    
    // Páginas
    for (const page of (pages.results || [])) {
      const p = page as { slug: string; updated_at: string };
      if (p.slug === 'home') continue; // Skip home, já incluída
      
      xml += `  <url>\n`;
      xml += `    <loc>${siteUrl}/${p.slug}</loc>\n`;
      xml += `    <lastmod>${new Date(p.updated_at).toISOString().split('T')[0]}</lastmod>\n`;
      xml += `    <changefreq>weekly</changefreq>\n`;
      xml += `    <priority>0.8</priority>\n`;
      xml += `  </url>\n`;
    }
    
    // Posts
    for (const post of (posts.results || [])) {
      const p = post as { slug: string; updated_at: string };
      
      xml += `  <url>\n`;
      xml += `    <loc>${siteUrl}/blog/${p.slug}</loc>\n`;
      xml += `    <lastmod>${new Date(p.updated_at).toISOString().split('T')[0]}</lastmod>\n`;
      xml += `    <changefreq>monthly</changefreq>\n`;
      xml += `    <priority>0.7</priority>\n`;
      xml += `  </url>\n`;
    }
    
    xml += '</urlset>';
    
    return new Response(xml, {
      headers: {
        'Content-Type': 'application/xml',
        'Cache-Control': 'public, max-age=3600', // 1 hora
      },
    });
  } catch (error) {
    console.error('Sitemap error:', error);
    return c.text('Error generating sitemap', 500);
  }
});

// ==================== ROBOTS.TXT ====================
seoRoutes.get('/robots.txt', async (c) => {
  try {
    const db = c.env.DB;
    
    // Buscar URL do site
    const settingsResult = await db.prepare(
      "SELECT value FROM settings WHERE key = 'site_url'"
    ).first();
    const siteUrl = (settingsResult?.value as string) || 'https://cms-site.pages.dev';
    
    const robots = `# Robots.txt for ${siteUrl}
# Generated by CMS Site

User-agent: *
Allow: /

# Sitemaps
Sitemap: ${siteUrl}/sitemap.xml

# Disallow admin and API
Disallow: /api/
Disallow: /admin/

# Allow search engines to index all public content
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /
`;
    
    return new Response(robots, {
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': 'public, max-age=86400', // 24 horas
      },
    });
  } catch (error) {
    console.error('Robots.txt error:', error);
    return c.text('Error generating robots.txt', 500);
  }
});

// ==================== SCHEMA.ORG JSON-LD ====================
seoRoutes.get('/schema.json', async (c) => {
  try {
    const db = c.env.DB;
    
    // Buscar configurações
    const settings = await db.prepare(`
      SELECT key, value FROM settings 
      WHERE key IN ('site_name', 'site_url', 'site_description', 'contact_email', 'contact_phone', 'contact_address', 'social_facebook', 'social_instagram', 'logo_url')
    `).all();
    
    const config: Record<string, string> = {};
    for (const s of (settings.results || [])) {
      const setting = s as { key: string; value: string };
      config[setting.key] = setting.value;
    }
    
    const siteUrl = config.site_url || 'https://cms-site.pages.dev';
    
    const schema = {
      '@context': 'https://schema.org',
      '@graph': [
        // Organization
        {
          '@type': 'Organization',
          '@id': `${siteUrl}/#organization`,
          'name': config.site_name || 'CMS Site',
          'url': siteUrl,
          'logo': config.logo_url ? {
            '@type': 'ImageObject',
            'url': config.logo_url,
          } : undefined,
          'description': config.site_description,
          'email': config.contact_email,
          'telephone': config.contact_phone,
          'address': config.contact_address ? {
            '@type': 'PostalAddress',
            'streetAddress': config.contact_address,
          } : undefined,
          'sameAs': [
            config.social_facebook,
            config.social_instagram,
          ].filter(Boolean),
        },
        // WebSite
        {
          '@type': 'WebSite',
          '@id': `${siteUrl}/#website`,
          'url': siteUrl,
          'name': config.site_name || 'CMS Site',
          'description': config.site_description,
          'publisher': {
            '@id': `${siteUrl}/#organization`,
          },
          'potentialAction': {
            '@type': 'SearchAction',
            'target': `${siteUrl}/busca?q={search_term_string}`,
            'query-input': 'required name=search_term_string',
          },
        },
      ],
    };
    
    return c.json(schema);
  } catch (error) {
    console.error('Schema error:', error);
    return c.json({ error: 'Error generating schema' }, 500);
  }
});
